require 'app/forked/themes/light-mode-theme.rb'
require 'app/forked/themes/dark-mode-theme.rb'
require 'app/forked/themes/kifass-theme.rb'
require 'app/forked/themes/20-second-theme.rb'
require 'app/forked/parse.rb'
require 'app/forked/input.rb'
require 'app/forked/display_defaults.rb'
require 'app/forked/display.rb'
require 'app/forked/author.rb'
require 'app/forked/forked.rb'
require 'app/forked/export.rb'

require 'app/tick.rb'
